spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/frauddb
    username: postgres
    password: merhi
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8083
